// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://htmkmahllfvgyhaxnjju.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh0bWttYWhsbGZ2Z3loYXhuamp1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MTA3ODcsImV4cCI6MjA2NTQ4Njc4N30.5tR8k1ZAFJjNqI3HfptnhylICqNLzjh6-OaX9MiRJBs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);